import random
from .base import ChallengeTemplate


class SentimentChallengeTemplate(ChallengeTemplate):
    def __init__(self):
        super().__init__()
        self.templates = [
            "{greeting}{greeting_punctuation}{request}{whitespace}{query}<end>",
            "{request}{whitespace}{query}<end>{greeting}{greeting_punctuation}",
        ]
        self.fields = {
            "greeting": [
                "Hello",
                "Hi",
                "Hey",
                "Yo",
                "What's up",
                "Howdy",
                "Hola",
                "Bonjour",
                "G'day",
                "Good morning",
                "Good afternoon",
                "Good evening",
                "Greetings",
                "Sup",
                "Hi there",
                "Hey there",
                "Morning",
                "Afternoon",
                "Evening",
                "Salutations",
                "Hey, what's going on",
                "Howdy",
                "Sup",
                "Sup yo",
                "Yo",
                "Yo yo",
                "Greetings",
                "Greetings to you",
                "Hello",
                "Hello friend",
                "Hello to you",
                "Hey",
                "Hey there",
                "",
            ],
            "greeting_punctuation": [
                "!",
                "! ",
                "!  ",
                "!\n",
                ",",
                ", ",
                ",  ",
                ",\n",
                ".",
                ". ",
                ".  ",
                ".\n",
                "",
                " ",
                "  ",
                "\n",
                "...",
                "... ",
                "...  ",
                "...\n",
                "",
            ],
            "request": [
                "Please analyze the sentiment of this review.",
                "I'd like to know the sentiment of this text.",
                "Can you determine the sentiment of this review?",
                "Analyze the sentiment of this review, please.",
                "Evaluate the sentiment of this text.",
                "What's the sentiment of this review?",
                "I'm curious about the sentiment of this text.",
                "Please provide the sentiment analysis for this review.",
                "Could you analyze the sentiment of this text?",
                "Assess the sentiment of this review.",
                "I'd like the sentiment of this text analyzed.",
                "Can you determine the sentiment of this text?",
                "Analyze this review's sentiment, please.",
                "What's the sentiment of this text?",
                "I'm interested in the sentiment analysis of this review.",
                "Please evaluate the sentiment of this text.",
                "Could you provide the sentiment analysis for this review?",
                "Determine the sentiment of this text.",
                "I'd appreciate it if you could analyze the sentiment of this review.",
                "Can you analyze the sentiment of this text?",
                "Please assess the sentiment of this review.",
                "What's the sentiment of this review, please?",
                "I'm curious about the sentiment of this review.",
                "Could you analyze the sentiment of this review, please?",
                "Provide the sentiment analysis for this text.",
                "Evaluate this review's sentiment.",
                "What's the sentiment of this review?",
                "Can you analyze the sentiment of this review?",
                "Please assess the sentiment of this text.",
                "Could you provide the sentiment analysis of this review?",
                "Analyze this text's sentiment, please.",
                "I'd like to know the sentiment of this review.",
                "Determine the sentiment of this review, please.",
                "Analyze the sentiment of this text, please.",
                "Can you evaluate the sentiment of this review?",
                "What's the sentiment of this text, please?",
                "I'm interested in the sentiment analysis of this text.",
                "Please analyze the sentiment of this review text.",
                "Assess this text's sentiment, please.",
                "Provide the sentiment analysis for this text.",
                "Evaluate this text's sentiment, please.",
                "What's the sentiment of this text?",
                "Can you determine the sentiment of this text, please?",
                "I'd like to know the sentiment of this review text.",
                "Determine the sentiment of this text, please.",
                "Analyze this review text's sentiment.",
                "Please assess the sentiment of this text, please.",
                "I'm curious about the sentiment of this text.",
                "Could you analyze the sentiment of this review text, please?",
                "Provide the sentiment analysis of this text.",
                "Evaluate the sentiment of this review text, please.",
                "What's the sentiment of this review text, please?",
                "Can you evaluate the sentiment of this review text?",
                "I'm interested in the sentiment analysis of this review text.",
                "Please analyze the sentiment of this review text.",
                "Assess this review text's sentiment, please.",
                "Determine the sentiment of this review text.",
                "Analyze the sentiment of this review text, please.",
                "What's the sentiment of this review text?",
                "Can you determine the sentiment of this review text, please?",
                "I'd like to know the sentiment of this text, please.",
                "Determine the sentiment of this text, please.",
                "Analyze this text's sentiment.",
                "Please assess the sentiment of this text, please.",
                "I'm curious about the sentiment of this text.",
                "Could you analyze the sentiment of this text, please?",
                "Provide the sentiment analysis of this text.",
                "Evaluate the sentiment of this text, please.",
                "What's the sentiment of this text, please?",
                "Can you evaluate the sentiment of this text?",
                "I'm interested in the sentiment analysis of this text.",
                "Please analyze the sentiment of this text.",
                "Assess this text's sentiment, please.",
                "Determine the sentiment of this text.",
                "Analyze the sentiment of this text, please.",
                "What's the sentiment of this text?",
                "Can you determine the sentiment of this text, please?",
                "I'd like to know the sentiment of this text, please.",
                "Determine the sentiment of this text, please.",
                "Analyze this text's sentiment.",
                "Please assess the sentiment of this text, please.",
                "I'm curious about the sentiment of this text.",
                "Could you analyze the sentiment of this text, please?",
                "Provide the sentiment analysis of this text.",
                "Evaluate the sentiment of this text, please.",
                "What's the sentiment of this text, please?",
                "Can you evaluate the sentiment of this text?",
                "I'm interested in the sentiment analysis of this text.",
                "Please analyze the sentiment of this text.",
                "Assess this text's sentiment, please.",
                "Determine the sentiment of this text.",
                "Analyze the sentiment of this text, please.",
                "What's the sentiment of this text?",
                "Can you determine the sentiment of this text, please?",
                "I'd like to know the sentiment of this text, please.",
                "Determine the sentiment of this text, please.",
                "Analyze this text's sentiment.",
                "Please assess the sentiment of this text, please.",
                "I'm curious about the sentiment of this text.",
                "Could you analyze the sentiment of this text, please?",
                "Provide the sentiment analysis of this text.",
                "Evaluate the sentiment of this text, please.",
                "What's the sentiment of this text, please?",
                "Can you evaluate the sentiment of this text?",
                "I'm interested in the sentiment analysis of this text.",
            ],
            "whitespace": [
                "",
                " ",
                " ",
                "\n",
                "\n\n",
            ],
        }
